ens_jobeet_job:
    resource: "@EnsJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /
    
default_hello:
    path: /hello/jobeet
    defaults: { _controller: EnsJobeetBundle:Default:index }
